# Config ini digenerate otomatis oleh ConfigManager::saveToFile
# Bisa juga diedit manual, format: key = value

input = rtsp://127.0.0.1:8554/video
model = ../models/best.engine
width = 1920
height = 1080
fps = 30
infer_size = 832
conf = 0.75
nms = 0.45
classes_enabled = 0,1,10,2,3,4,5,6,7,8,9
rtsp_port = 8555
rtsp_mount = /live
ip_address = 192.168.168.142
gstreamer = true
reconnect_interval_ms = 2000
show_overlay = true
encoder_type = nvidia_gpu
codec_type = h265
bitrate_kbps = 4000
api_port = 8765
api_host = 127.0.0.1
is_detection = true
is_crowd_counting = true
crowd_model = ../models/model_qnrf.engine
crowd_input_width = 1024
crowd_input_height = 768
crowd_infer_interval = 5
