# ==========================================================
# config.ini - konfigurasi yolo_local_test
# Edit file ini untuk mengubah setting TANPA compile ulang.
# Baris diawali '#' atau ';' dianggap komentar.
# ==========================================================

# Sumber input: index kamera (0,1,...) atau path device (/dev/video0) atau path file video
input = rtsp://127.0.0.1:8554/video
; input = /dev/video0
# Konfigurasi RTSP Input Source
gstreamer = true
# Path ke model TensorRT engine
model = ../models/yolo11s.engine

show_overlay = false

# Resolusi & framerate capture
width = 1280
height = 720
fps = 30

# Ukuran input inferensi (samakan dengan saat export model!)
infer_size = 640

# Threshold confidence & NMS
conf = 0.50
nms = 0.45

# Filter class id yang mau dideteksi, pisahkan dengan koma.
# Kosongkan untuk mendeteksi semua class.
# target_classes = 0

# Konfigurasi RTSP server
rtsp_port = 8555
rtsp_mount = /live
ip_address = 192.168.168.136
