
# API CONTROLLER
api_host = 127.0.0.1
api_port = 8765

# YOLO DETECTOR
model = ../models/best.engine
infer_size = 832
conf = 0.50
nms = 0.45
target_classes = 0,1,2,3,5,7
show_overlay = true

# SOURCE HANDLER
input = rtsp://127.0.0.1:8554/video
# input = /dev/video0
gstreamer = true
width = 1280
height = 720
fps = 30
reconnect_interval_ms = 2000

# RTSP SERVER
rtsp_port = 8555
rtsp_mount = /live
ip_address = 192.168.168.142
# cpu | nvidia_gpu | jetson
encoder_type = nvidia_gpu
# h264 | h265
codec_type = h265
bitrate_kbps = 2000
